[workspace]
authors = ["Robert Cocker <robert.cocker@mavs.uta.edu>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly/"]
name = "dataproblems"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.3.1,<3"
seaborn = ">=0.13.2,<0.14"
matplotlib = ">=3.10.3,<4"
pandas = ">=2.3.0,<3"
scikit-learn = ">=1.7.0,<2"
modular = ">=25.5.0.dev2025070705,<26"
max = ">=25.5.0.dev2025070705,<26"
max-pipelines = ">=25.5.0.dev2025070705,<26"
keras = ">=3.10.0,<4"
