[workspace]
authors = ["Robert Cocker <robert.cocker@mavs.uta.edu>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly/"]
name = "dataproblems"
platforms = ["linux-64"]
version = "0.2.0"

[tasks]

[dependencies]
numpy = ">=1.19.5,<2"
seaborn = ">=0.12.2,<0.13"
matplotlib = ">=3.5.3,<4"
pandas = ">=1.4.4,<2"
scikit-learn = ">=1.6.1,<2"
python = ">=3.9.15,<3.10"
tensorflow = ">=2.6.2,<3"
keras = ">=2.6.0,<3"
jupyter = ">=1.1.1,<2"
notebook = ">=7.4.5,<8"
pydot = ">=4.0.1,<5"
jupytext = ">=1.17.2,<2"
nbconvert = ">=7.16.6,<8"
nbformat = ">=5.10.4,<6"
unrar = ">=0.4,<0.5"

[pypi-dependencies]
tensorflow-keras = ">=0.1, <0.2"
